spring:
  bot:
    plugin-list: # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
      - com.wisdomguo.xifeng.plugin.XFPlugin #基础曹组哟
      - com.wisdomguo.xifeng.plugin.SetXFPlugin #惜风设置
      - com.wisdomguo.xifeng.plugin.OtherPlugin #其他功能
      - com.wisdomguo.xifeng.plugin.HelpPlugin #帮助列表
      - com.wisdomguo.xifeng.plugin.GroupPlugin #群管理功能
      - com.wisdomguo.xifeng.plugin.DicePlugin #骰子功能
      - com.wisdomguo.xifeng.plugin.CardPlugin #人物卡功能
      - com.wisdomguo.xifeng.plugin.LogPlugin # 日志插件
      - com.wisdomguo.xifeng.plugin.HarukaBotPlugin # 排班系统
      - com.wisdomguo.xifeng.plugin.LuckMutePlugin # 禁言随机

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/wisdombot?useSSL=false
    url: jdbc:mysql://47.113.231.84:3306/wisdombot?useSSL=false
    username: root
    password: 140610
  thymeleaf:
    cache: false

mybatis-plus:
  #mapper路径
  mapper-locations: classpath:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wisdomguo.**.entity
  #通用枚举扫描
  typeEnumsPackage: com.wisdomguo.**.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: ASSIGN_ID
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

server:
  port: 8888